// _legacy-react/src/app/pages/RegisterPet.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router';
import { Box, Container, Paper, Typography, TextField, Button, Grid, Select, MenuItem, FormControl, InputLabel, IconButton } from '@mui/material';
import { ArrowLeft, Upload, Save, X } from 'lucide-react';
import Sidebar from '../components/Sidebar';
import Topbar from '../components/Topbar';
import Footer from '../components/Footer';

export default function RegisterPet() {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    name: '',
    species: '',
    breed: '',
    age: '',
    sex: '',
    weight: '',
    vaccines: '',
    allergies: '',
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Guardar mascota
    navigate('/client');
  };

  const handleChange = (field: string, value: string) => {
    setFormData({ ...formData, [field]: value });
  };

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', bgcolor: '#F8FAFC', minHeight: '100vh' }}>
      <Box sx={{ display: 'flex', flex: 1 }}>
        <Sidebar isAdmin={false} />

        <Box sx={{ flexGrow: 1, ml: '260px' }}>
          <Topbar userName="María López" userRole="Cliente" />

        <Container maxWidth="md" sx={{ mt: 10, py: 4 }}>
          <Button
            startIcon={<ArrowLeft size={20} />}
            onClick={() => navigate('/client')}
            sx={{ mb: 3, color: '#64748B' }}
          >
            Volver
          </Button>

          <Paper sx={{ p: 4, borderRadius: 3, border: '1px solid #E2E8F0' }}>
            <Typography variant="h4" sx={{ mb: 1, fontWeight: 700, color: '#1E293B' }}>
              Registrar Nueva Mascota
            </Typography>
            <Typography variant="body2" sx={{ mb: 4, color: '#64748B' }}>
              Completa la información de tu mascota para crear su perfil médico
            </Typography>

            <form onSubmit={handleSubmit}>
              <Grid container spacing={3}>
                {/* Photo Upload */}
                <Grid item xs={12}>
                  <Box
                    sx={{
                      border: '2px dashed #CBD5E1',
                      borderRadius: 3,
                      p: 4,
                      textAlign: 'center',
                      cursor: 'pointer',
                      '&:hover': { borderColor: '#2563EB', bgcolor: '#F8FAFC' },
                    }}
                  >
                    <Upload size={48} color="#64748B" style={{ marginBottom: 16 }} />
                    <Typography variant="body1" sx={{ color: '#64748B', mb: 1 }}>
                      Subir fotografía de tu mascota
                    </Typography>
                    <Typography variant="caption" sx={{ color: '#94A3B8' }}>
                      PNG, JPG hasta 5MB
                    </Typography>
                  </Box>
                </Grid>

                {/* Basic Info */}
                <Grid item xs={12} sm={6}>
                  <TextField
                    fullWidth
                    label="Nombre"
                    value={formData.name}
                    onChange={(e) => handleChange('name', e.target.value)}
                    required
                  />
                </Grid>

                <Grid item xs={12} sm={6}>
                  <FormControl fullWidth required>
                    <InputLabel>Especie</InputLabel>
                    <Select
                      value={formData.species}
                      label="Especie"
                      onChange={(e) => handleChange('species', e.target.value)}
                    >
                      <MenuItem value="perro">Perro</MenuItem>
                      <MenuItem value="gato">Gato</MenuItem>
                      <MenuItem value="ave">Ave</MenuItem>
                      <MenuItem value="conejo">Conejo</MenuItem>
                      <MenuItem value="otro">Otro</MenuItem>
                    </Select>
                  </FormControl>
                </Grid>

                <Grid item xs={12} sm={6}>
                  <TextField
                    fullWidth
                    label="Raza"
                    value={formData.breed}
                    onChange={(e) => handleChange('breed', e.target.value)}
                    required
                  />
                </Grid>

                <Grid item xs={12} sm={6}>
                  <TextField
                    fullWidth
                    label="Edad"
                    value={formData.age}
                    onChange={(e) => handleChange('age', e.target.value)}
                    placeholder="Ej: 3 años"
                    required
                  />
                </Grid>

                <Grid item xs={12} sm={6}>
                  <FormControl fullWidth required>
                    <InputLabel>Sexo</InputLabel>
                    <Select
                      value={formData.sex}
                      label="Sexo"
                      onChange={(e) => handleChange('sex', e.target.value)}
                    >
                      <MenuItem value="macho">Macho</MenuItem>
                      <MenuItem value="hembra">Hembra</MenuItem>
                    </Select>
                  </FormControl>
                </Grid>

                <Grid item xs={12} sm={6}>
                  <TextField
                    fullWidth
                    label="Peso"
                    value={formData.weight}
                    onChange={(e) => handleChange('weight', e.target.value)}
                    placeholder="Ej: 15 kg"
                    required
                  />
                </Grid>

                {/* Medical Info */}
                <Grid item xs={12}>
                  <TextField
                    fullWidth
                    label="Vacunas Aplicadas"
                    value={formData.vaccines}
                    onChange={(e) => handleChange('vaccines', e.target.value)}
                    multiline
                    rows={3}
                    placeholder="Lista de vacunas que tiene tu mascota..."
                  />
                </Grid>

                <Grid item xs={12}>
                  <TextField
                    fullWidth
                    label="Alergias o Condiciones Médicas"
                    value={formData.allergies}
                    onChange={(e) => handleChange('allergies', e.target.value)}
                    multiline
                    rows={3}
                    placeholder="Describe cualquier alergia o condición médica conocida..."
                  />
                </Grid>

                {/* Actions */}
                <Grid item xs={12}>
                  <Box sx={{ display: 'flex', gap: 2, justifyContent: 'flex-end', mt: 2 }}>
                    <Button
                      variant="outlined"
                      onClick={() => navigate('/client')}
                      startIcon={<X size={18} />}
                      sx={{ px: 3, py: 1.5 }}
                    >
                      Cancelar
                    </Button>
                    <Button
                      type="submit"
                      variant="contained"
                      startIcon={<Save size={18} />}
                      sx={{
                        bgcolor: '#2563EB',
                        '&:hover': { bgcolor: '#1E40AF' },
                        px: 3,
                        py: 1.5,
                        fontWeight: 600,
                      }}
                    >
                      Guardar Mascota
                    </Button>
                  </Box>
                </Grid>
              </Grid>
            </form>
          </Paper>
        </Container>
        </Box>
      </Box>

      <Footer />
    </Box>
  );
}

// src/app/pages/client/register-pet/register-pet.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { LucideIconComponent } from '../../../shared/components/lucide-icon/lucide-icon.component';

interface PetForm {
  name: string;
  species: string;
  breed: string;
  age: string;
  sex: string;
  weight: string;
  vaccines: string;
  allergies: string;
}

@Component({
  selector: 'app-register-pet',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    LucideIconComponent,
  ],
  templateUrl: './register-pet.component.html',
  styleUrl: './register-pet.component.scss',
})
export class RegisterPetComponent {
  formData = signal<PetForm>({
    name: '',
    species: '',
    breed: '',
    age: '',
    sex: '',
    weight: '',
    vaccines: '',
    allergies: '',
  });

  constructor(private readonly router: Router) {}

  handleChange(field: keyof PetForm, value: string): void {
    this.formData.update((prev) => ({ ...prev, [field]: value }));
  }

  handleSubmit(event: Event): void {
    event.preventDefault();
    this.router.navigate(['/client']);
  }

  goBack(): void {
    this.router.navigate(['/client']);
  }
}

<div class="page-container page-container--narrow">
  <button mat-button class="back-btn" type="button" (click)="goBack()">
    <app-lucide-icon name="arrow-left" [size]="20" />
    Volver
  </button>

  <mat-card class="form-card">
    <h1 class="page-title">Registrar Nueva Mascota</h1>
    <p class="page-subtitle">Completa la información de tu mascota para crear su perfil médico</p>

    <form (submit)="handleSubmit($event)">
      <div class="upload-zone">
        <app-lucide-icon name="upload" [size]="48" color="#64748B" />
        <p>Subir fotografía de tu mascota</p>
        <span>PNG, JPG hasta 5MB</span>
      </div>

      <div class="form-grid">
        <mat-form-field appearance="outline">
          <mat-label>Nombre</mat-label>
          <input matInput required [ngModel]="formData().name" (ngModelChange)="handleChange('name', $event)" name="name" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Especie</mat-label>
          <mat-select required [ngModel]="formData().species" (ngModelChange)="handleChange('species', $event)" name="species">
            <mat-option value="perro">Perro</mat-option>
            <mat-option value="gato">Gato</mat-option>
            <mat-option value="ave">Ave</mat-option>
            <mat-option value="conejo">Conejo</mat-option>
            <mat-option value="otro">Otro</mat-option>
          </mat-select>
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Raza</mat-label>
          <input matInput required [ngModel]="formData().breed" (ngModelChange)="handleChange('breed', $event)" name="breed" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Edad</mat-label>
          <input matInput required placeholder="Ej: 3 años" [ngModel]="formData().age" (ngModelChange)="handleChange('age', $event)" name="age" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Sexo</mat-label>
          <mat-select required [ngModel]="formData().sex" (ngModelChange)="handleChange('sex', $event)" name="sex">
            <mat-option value="macho">Macho</mat-option>
            <mat-option value="hembra">Hembra</mat-option>
          </mat-select>
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Peso</mat-label>
          <input matInput required placeholder="Ej: 15 kg" [ngModel]="formData().weight" (ngModelChange)="handleChange('weight', $event)" name="weight" />
        </mat-form-field>
        <mat-form-field appearance="outline" class="full-span">
          <mat-label>Vacunas Aplicadas</mat-label>
          <textarea matInput rows="3" placeholder="Lista de vacunas que tiene tu mascota..." [ngModel]="formData().vaccines" (ngModelChange)="handleChange('vaccines', $event)" name="vaccines"></textarea>
        </mat-form-field>
        <mat-form-field appearance="outline" class="full-span">
          <mat-label>Alergias o Condiciones Médicas</mat-label>
          <textarea matInput rows="3" placeholder="Describe cualquier alergia o condición médica conocida..." [ngModel]="formData().allergies" (ngModelChange)="handleChange('allergies', $event)" name="allergies"></textarea>
        </mat-form-field>
      </div>

      <div class="form-actions">
        <button mat-stroked-button type="button" (click)="goBack()">
          <app-lucide-icon name="x" [size]="18" />
          Cancelar
        </button>
        <button mat-flat-button class="btn-primary" type="submit">
          <app-lucide-icon name="save" [size]="18" />
          Guardar Mascota
        </button>
      </div>
    </form>
  </mat-card>
</div>
