// src/app/pages/admin/medical-history/medical-history.component.ts
import { Component, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatChipsModule } from '@angular/material/chips';
import { LucideIconComponent } from '../../../shared/components/lucide-icon/lucide-icon.component';

const medicalRecords = [
  { id: 1, date: '2026-05-20', type: 'Consulta General', pet: 'Max', doctor: 'Dr. Juan Pérez', diagnosis: 'Chequeo de rutina - Estado de salud óptimo', treatment: 'Ninguno', medications: [] as string[], notes: 'Mascota saludable. Peso adecuado. Recomendaciones de dieta mantenidas.' },
  { id: 2, date: '2026-05-15', type: 'Vacunación', pet: 'Luna', doctor: 'Dra. María González', diagnosis: 'Aplicación de vacuna antirrábica anual', treatment: 'Vacuna antirrábica', medications: ['Vacuna Rabia - 1ml'], notes: 'Próxima vacuna en mayo 2027. Sin reacciones adversas.' },
  { id: 3, date: '2026-05-10', type: 'Emergencia', pet: 'Rocky', doctor: 'Dr. Luis Martínez', diagnosis: 'Fractura en pata trasera derecha', treatment: 'Cirugía de reducción y fijación', medications: ['Tramadol 50mg', 'Antibiótico - Cefalexina 500mg'], notes: 'Cirugía exitosa. Reposo absoluto por 6 semanas. Control en 10 días.' },
  { id: 4, date: '2026-05-05', type: 'Tratamiento', pet: 'Bella', doctor: 'Dra. Ana García', diagnosis: 'Infección en oído izquierdo', treatment: 'Limpieza profunda y medicación tópica', medications: ['Gotas óticas antibióticas', 'Antiinflamatorio oral'], notes: 'Aplicar gotas 2 veces al día por 10 días. Control en 1 semana.' },
  { id: 5, date: '2026-04-28', type: 'Consulta Especializada', pet: 'Milo', doctor: 'Dr. Juan Pérez', diagnosis: 'Problemas dermatológicos - Alergias alimentarias', treatment: 'Cambio de dieta y tratamiento tópico', medications: ['Shampoo medicado', 'Antihistamínico'], notes: 'Dieta hipoalergénica estricta. Eliminar pollo y cereales.' },
];

@Component({
  selector: 'app-medical-history',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatChipsModule,
    LucideIconComponent,
  ],
  templateUrl: './medical-history.component.html',
  styleUrl: './medical-history.component.scss',
})
export class MedicalHistoryComponent {
  searchTerm = signal('');

  filteredRecords = computed(() => {
    const term = this.searchTerm().toLowerCase();
    return medicalRecords.filter(
      (r) =>
        r.pet.toLowerCase().includes(term) ||
        r.diagnosis.toLowerCase().includes(term) ||
        r.doctor.toLowerCase().includes(term),
    );
  });

  getTypeConfig(type: string): { bg: string; color: string; icon: string } {
    switch (type) {
      case 'Consulta General': return { bg: '#DBEAFE', color: '#2563EB', icon: 'stethoscope' };
      case 'Vacunación': return { bg: '#D1FAE5', color: '#10B981', icon: 'syringe' };
      case 'Emergencia': return { bg: '#FEE2E2', color: '#EF4444', icon: 'alert-circle' };
      case 'Tratamiento': return { bg: '#FED7AA', color: '#F59E0B', icon: 'pill' };
      case 'Consulta Especializada': return { bg: '#E9D5FF', color: '#A855F7', icon: 'file-text' };
      default: return { bg: '#E2E8F0', color: '#64748B', icon: 'file-text' };
    }
  }
}

<div class="page-container">
  <div class="page-header">
    <div>
      <h1 class="page-title">Historial Médico</h1>
      <p class="page-subtitle">Registro completo de consultas, tratamientos y medicamentos</p>
    </div>
    <button mat-flat-button class="btn-primary">
      <app-lucide-icon name="download" [size]="20" />
      Exportar Historial
    </button>
  </div>

  <mat-card class="search-card">
    <mat-form-field appearance="outline" class="search-field">
      <app-lucide-icon matPrefix name="search" [size]="20" color="#64748B" />
      <input matInput placeholder="Buscar por mascota, diagnóstico o veterinario..." [ngModel]="searchTerm()" (ngModelChange)="searchTerm.set($event)" />
    </mat-form-field>
  </mat-card>

  <div class="timeline">
    <div class="timeline__line"></div>
    @for (record of filteredRecords(); track record.id) {
      <div class="timeline__item">
        <div
          class="timeline__dot"
          [style.background]="getTypeConfig(record.type).bg"
          [style.border-color]="getTypeConfig(record.type).color"
        ></div>
        <mat-card class="record-card">
          <div class="record-card__grid">
            <div class="record-card__sidebar">
              <div class="record-card__icon" [style.background]="getTypeConfig(record.type).bg">
                <app-lucide-icon [name]="getTypeConfig(record.type).icon" [size]="24" [color]="getTypeConfig(record.type).color" />
              </div>
              <mat-chip [style.background]="getTypeConfig(record.type).bg" [style.color]="getTypeConfig(record.type).color">
                {{ record.type }}
              </mat-chip>
              <div class="record-card__date">
                <app-lucide-icon name="calendar" [size]="16" color="#64748B" />
                <span>{{ record.date }}</span>
              </div>
              <h3 class="record-card__pet">{{ record.pet }}</h3>
              <p class="record-card__doctor">{{ record.doctor }}</p>
            </div>
            <div class="record-card__content">
              <p class="record-card__section-title">Diagnóstico</p>
              <p class="record-card__text">{{ record.diagnosis }}</p>
              <div class="record-card__cols">
                <div>
                  <p class="record-card__section-title">Tratamiento</p>
                  <p class="record-card__text">{{ record.treatment }}</p>
                </div>
                @if (record.medications.length > 0) {
                  <div>
                    <p class="record-card__section-title">Medicamentos</p>
                    <div class="record-card__meds">
                      @for (med of record.medications; track med) {
                        <mat-chip class="med-chip">{{ med }}</mat-chip>
                      }
                    </div>
                  </div>
                }
              </div>
              <p class="record-card__section-title">Observaciones</p>
              <div class="record-card__notes">
                <p>{{ record.notes }}</p>
              </div>
            </div>
          </div>
        </mat-card>
      </div>
    }
  </div>
</div>

// _legacy-react/src/app/pages/MedicalHistory.tsx
import { useState } from 'react';
import { Box, Container, Paper, Typography, Chip, Button, TextField, InputAdornment, Grid, Avatar } from '@mui/material';
import { Search, FileText, Pill, Syringe, Stethoscope, AlertCircle, Calendar, Download } from 'lucide-react';
import Sidebar from '../components/Sidebar';
import Topbar from '../components/Topbar';

const medicalRecords = [
  {
    id: 1,
    date: '2026-05-20',
    type: 'Consulta General',
    pet: 'Max',
    doctor: 'Dr. Juan Pérez',
    diagnosis: 'Chequeo de rutina - Estado de salud óptimo',
    treatment: 'Ninguno',
    medications: [],
    notes: 'Mascota saludable. Peso adecuado. Recomendaciones de dieta mantenidas.',
  },
  {
    id: 2,
    date: '2026-05-15',
    type: 'Vacunación',
    pet: 'Luna',
    doctor: 'Dra. María González',
    diagnosis: 'Aplicación de vacuna antirrábica anual',
    treatment: 'Vacuna antirrábica',
    medications: ['Vacuna Rabia - 1ml'],
    notes: 'Próxima vacuna en mayo 2027. Sin reacciones adversas.',
  },
  {
    id: 3,
    date: '2026-05-10',
    type: 'Emergencia',
    pet: 'Rocky',
    doctor: 'Dr. Luis Martínez',
    diagnosis: 'Fractura en pata trasera derecha',
    treatment: 'Cirugía de reducción y fijación',
    medications: ['Tramadol 50mg', 'Antibiótico - Cefalexina 500mg'],
    notes: 'Cirugía exitosa. Reposo absoluto por 6 semanas. Control en 10 días.',
  },
  {
    id: 4,
    date: '2026-05-05',
    type: 'Tratamiento',
    pet: 'Bella',
    doctor: 'Dra. Ana García',
    diagnosis: 'Infección en oído izquierdo',
    treatment: 'Limpieza profunda y medicación tópica',
    medications: ['Gotas óticas antibióticas', 'Antiinflamatorio oral'],
    notes: 'Aplicar gotas 2 veces al día por 10 días. Control en 1 semana.',
  },
  {
    id: 5,
    date: '2026-04-28',
    type: 'Consulta Especializada',
    pet: 'Milo',
    doctor: 'Dr. Juan Pérez',
    diagnosis: 'Problemas dermatológicos - Alergias alimentarias',
    treatment: 'Cambio de dieta y tratamiento tópico',
    medications: ['Shampoo medicado', 'Antihistamínico'],
    notes: 'Dieta hipoalergénica estricta. Eliminar pollo y cereales.',
  },
];

export default function MedicalHistory() {
  const [searchTerm, setSearchTerm] = useState('');

  const getTypeConfig = (type: string) => {
    switch (type) {
      case 'Consulta General':
        return { bg: '#DBEAFE', color: '#2563EB', icon: Stethoscope };
      case 'Vacunación':
        return { bg: '#D1FAE5', color: '#10B981', icon: Syringe };
      case 'Emergencia':
        return { bg: '#FEE2E2', color: '#EF4444', icon: AlertCircle };
      case 'Tratamiento':
        return { bg: '#FED7AA', color: '#F59E0B', icon: Pill };
      case 'Consulta Especializada':
        return { bg: '#E9D5FF', color: '#A855F7', icon: FileText };
      default:
        return { bg: '#E2E8F0', color: '#64748B', icon: FileText };
    }
  };

  const filteredRecords = medicalRecords.filter(
    (record) =>
      record.pet.toLowerCase().includes(searchTerm.toLowerCase()) ||
      record.diagnosis.toLowerCase().includes(searchTerm.toLowerCase()) ||
      record.doctor.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <Box sx={{ display: 'flex', bgcolor: '#F8FAFC', minHeight: '100vh' }}>
      <Sidebar isAdmin={true} />

      <Box sx={{ flexGrow: 1, ml: '260px' }}>
        <Topbar userName="Dr. Juan Pérez" userRole="Veterinario Principal" />

        <Container maxWidth="xl" sx={{ mt: 10, py: 4 }}>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 4 }}>
            <Box>
              <Typography variant="h4" sx={{ fontWeight: 700, color: '#1E293B' }}>
                Historial Médico
              </Typography>
              <Typography variant="body2" sx={{ color: '#64748B', mt: 1 }}>
                Registro completo de consultas, tratamientos y medicamentos
              </Typography>
            </Box>
            <Button
              variant="contained"
              startIcon={<Download size={20} />}
              sx={{
                bgcolor: '#2563EB',
                '&:hover': { bgcolor: '#1E40AF' },
                px: 3,
                py: 1.5,
                fontWeight: 600,
              }}
            >
              Exportar Historial
            </Button>
          </Box>

          {/* Search */}
          <Paper sx={{ p: 2, mb: 4, borderRadius: 3, border: '1px solid #E2E8F0' }}>
            <TextField
              fullWidth
              placeholder="Buscar por mascota, diagnóstico o veterinario..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <Search size={20} color="#64748B" />
                  </InputAdornment>
                ),
              }}
              sx={{ '& .MuiOutlinedInput-root': { border: 'none' } }}
            />
          </Paper>

          {/* Timeline */}
          <Box sx={{ position: 'relative' }}>
            {/* Timeline Line */}
            <Box
              sx={{
                position: 'absolute',
                left: 20,
                top: 0,
                bottom: 0,
                width: 2,
                bgcolor: '#E2E8F0',
              }}
            />

            {filteredRecords.map((record, index) => {
              const typeConfig = getTypeConfig(record.type);
              const TypeIcon = typeConfig.icon;

              return (
                <Box key={record.id} sx={{ position: 'relative', mb: 4 }}>
                  {/* Timeline Dot */}
                  <Box
                    sx={{
                      position: 'absolute',
                      left: 8,
                      top: 30,
                      width: 24,
                      height: 24,
                      borderRadius: '50%',
                      bgcolor: typeConfig.bg,
                      border: `3px solid ${typeConfig.color}`,
                      zIndex: 1,
                    }}
                  />

                  <Paper
                    sx={{
                      ml: 8,
                      p: 3,
                      borderRadius: 3,
                      border: '1px solid #E2E8F0',
                      transition: 'all 0.2s',
                      '&:hover': {
                        boxShadow: '0 8px 24px rgba(0,0,0,0.1)',
                        transform: 'translateX(4px)',
                      },
                    }}
                  >
                    <Grid container spacing={3}>
                      <Grid item xs={12} md={3}>
                        <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
                          <Box sx={{ bgcolor: typeConfig.bg, p: 1.5, borderRadius: 2, mr: 2 }}>
                            <TypeIcon size={24} color={typeConfig.color} />
                          </Box>
                          <Box>
                            <Chip
                              label={record.type}
                              size="small"
                              sx={{
                                bgcolor: typeConfig.bg,
                                color: typeConfig.color,
                                fontWeight: 600,
                              }}
                            />
                          </Box>
                        </Box>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
                          <Calendar size={16} color="#64748B" />
                          <Typography variant="body2" sx={{ color: '#64748B' }}>
                            {record.date}
                          </Typography>
                        </Box>
                        <Typography variant="h6" sx={{ fontWeight: 700, mb: 0.5 }}>
                          {record.pet}
                        </Typography>
                        <Typography variant="caption" sx={{ color: '#64748B' }}>
                          {record.doctor}
                        </Typography>
                      </Grid>

                      <Grid item xs={12} md={9}>
                        <Typography variant="body1" sx={{ fontWeight: 600, mb: 2 }}>
                          Diagnóstico
                        </Typography>
                        <Typography variant="body2" sx={{ color: '#64748B', mb: 3 }}>
                          {record.diagnosis}
                        </Typography>

                        <Grid container spacing={3}>
                          <Grid item xs={12} sm={6}>
                            <Typography variant="body2" sx={{ fontWeight: 600, mb: 1 }}>
                              Tratamiento
                            </Typography>
                            <Typography variant="body2" sx={{ color: '#64748B' }}>
                              {record.treatment}
                            </Typography>
                          </Grid>

                          {record.medications.length > 0 && (
                            <Grid item xs={12} sm={6}>
                              <Typography variant="body2" sx={{ fontWeight: 600, mb: 1 }}>
                                Medicamentos
                              </Typography>
                              {record.medications.map((med, idx) => (
                                <Chip
                                  key={idx}
                                  label={med}
                                  size="small"
                                  sx={{
                                    mr: 1,
                                    mb: 1,
                                    bgcolor: '#F1F5F9',
                                    color: '#475569',
                                  }}
                                />
                              ))}
                            </Grid>
                          )}

                          <Grid item xs={12}>
                            <Typography variant="body2" sx={{ fontWeight: 600, mb: 1 }}>
                              Observaciones
                            </Typography>
                            <Box
                              sx={{
                                p: 2,
                                bgcolor: '#F8FAFC',
                                borderRadius: 2,
                                borderLeft: '3px solid #2563EB',
                              }}
                            >
                              <Typography variant="body2" sx={{ color: '#475569' }}>
                                {record.notes}
                              </Typography>
                            </Box>
                          </Grid>
                        </Grid>
                      </Grid>
                    </Grid>
                  </Paper>
                </Box>
              );
            })}
          </Box>
        </Container>
      </Box>
    </Box>
  );
}
