// src/app/pages/admin/settings/settings.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { LucideIconComponent } from '../../../shared/components/lucide-icon/lucide-icon.component';

interface NotificationSettings {
  email: boolean;
  sms: boolean;
  emergencias: boolean;
  citas: boolean;
  reportes: boolean;
}

@Component({
  selector: 'app-settings',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatSlideToggleModule,
    LucideIconComponent,
  ],
  templateUrl: './settings.component.html',
  styleUrl: './settings.component.scss',
})
export class SettingsComponent {
  notifications = signal<NotificationSettings>({
    email: true,
    sms: false,
    emergencias: true,
    citas: true,
    reportes: false,
  });

  updateNotification(key: keyof NotificationSettings, value: boolean): void {
    this.notifications.update((prev) => ({ ...prev, [key]: value }));
  }
}

<div class="page-container settings-page">
  <h1 class="page-title">Configuración</h1>

  <mat-card class="settings-section">
    <div class="settings-section__header">
      <app-lucide-icon name="user" [size]="24" color="#2563EB" />
      <h2>Perfil Personal</h2>
    </div>
    <div class="profile-grid">
      <div class="profile-avatar-block">
        <div class="profile-avatar">JP</div>
        <button mat-stroked-button>Cambiar Foto</button>
      </div>
      <div class="profile-fields">
        <div class="fields-grid">
          <mat-form-field appearance="outline"><mat-label>Nombre</mat-label><input matInput value="Dr. Juan Pérez" /></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>Correo Electrónico</mat-label><input matInput value="juan.perez@petalert.com" /></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>Teléfono</mat-label><input matInput value="+1 234-567-8901" /></mat-form-field>
          <mat-form-field appearance="outline"><mat-label>Especialidad</mat-label><input matInput value="Cirugía General" /></mat-form-field>
          <mat-form-field appearance="outline" class="full-span">
            <mat-label>Biografía</mat-label>
            <textarea matInput rows="3">Veterinario con 10 años de experiencia en cirugía general y emergencias.</textarea>
          </mat-form-field>
        </div>
      </div>
    </div>
    <div class="settings-section__footer">
      <button mat-flat-button class="btn-primary"><app-lucide-icon name="save" [size]="18" /> Guardar Cambios</button>
    </div>
  </mat-card>

  <mat-card class="settings-section">
    <div class="settings-section__header">
      <app-lucide-icon name="building" [size]="24" color="#2563EB" />
      <h2>Información de la Clínica</h2>
    </div>
    <div class="fields-grid">
      <mat-form-field appearance="outline"><mat-label>Nombre de la Clínica</mat-label><input matInput value="Clínica Veterinaria PetAlert" /></mat-form-field>
      <mat-form-field appearance="outline"><mat-label>Teléfono Principal</mat-label><input matInput value="+1 800-PET-ALERT" /></mat-form-field>
      <mat-form-field appearance="outline" class="full-span"><mat-label>Dirección</mat-label><input matInput value="123 Calle Principal, Ciudad, País" /></mat-form-field>
      <mat-form-field appearance="outline"><mat-label>Horario de Atención</mat-label><input matInput value="Lun-Vie: 8AM - 8PM" /></mat-form-field>
      <mat-form-field appearance="outline"><mat-label>Email de Contacto</mat-label><input matInput value="info@petalert.com" /></mat-form-field>
    </div>
    <div class="settings-section__footer">
      <button mat-flat-button class="btn-primary"><app-lucide-icon name="save" [size]="18" /> Guardar Cambios</button>
    </div>
  </mat-card>

  <mat-card class="settings-section">
    <div class="settings-section__header">
      <app-lucide-icon name="bell" [size]="24" color="#2563EB" />
      <h2>Notificaciones</h2>
    </div>
    <div class="toggles-list">
      <mat-slide-toggle [checked]="notifications().email" (change)="updateNotification('email', $event.checked)">
        Notificaciones por correo electrónico
      </mat-slide-toggle>
      <mat-slide-toggle [checked]="notifications().sms" (change)="updateNotification('sms', $event.checked)">
        Notificaciones por SMS
      </mat-slide-toggle>
      <hr class="divider" />
      <p class="toggles-list__subtitle">Tipos de Notificaciones</p>
      <mat-slide-toggle [checked]="notifications().emergencias" (change)="updateNotification('emergencias', $event.checked)">
        Alertas de emergencias
      </mat-slide-toggle>
      <mat-slide-toggle [checked]="notifications().citas" (change)="updateNotification('citas', $event.checked)">
        Recordatorios de citas
      </mat-slide-toggle>
      <mat-slide-toggle [checked]="notifications().reportes" (change)="updateNotification('reportes', $event.checked)">
        Reportes semanales
      </mat-slide-toggle>
    </div>
    <div class="settings-section__footer">
      <button mat-flat-button class="btn-primary"><app-lucide-icon name="save" [size]="18" /> Guardar Preferencias</button>
    </div>
  </mat-card>

  <mat-card class="settings-section">
    <div class="settings-section__header">
      <app-lucide-icon name="lock" [size]="24" color="#2563EB" />
      <h2>Seguridad</h2>
    </div>
    <div class="fields-grid">
      <mat-form-field appearance="outline" class="full-span">
        <mat-label>Contraseña Actual</mat-label>
        <input matInput type="password" placeholder="Ingresa tu contraseña actual" />
      </mat-form-field>
      <mat-form-field appearance="outline"><mat-label>Nueva Contraseña</mat-label><input matInput type="password" placeholder="Ingresa nueva contraseña" /></mat-form-field>
      <mat-form-field appearance="outline"><mat-label>Confirmar Contraseña</mat-label><input matInput type="password" placeholder="Confirma tu nueva contraseña" /></mat-form-field>
    </div>
    <div class="settings-section__footer">
      <button mat-flat-button class="btn-primary"><app-lucide-icon name="lock" [size]="18" /> Cambiar Contraseña</button>
    </div>
  </mat-card>

  <mat-card class="settings-section">
    <div class="settings-section__header">
      <app-lucide-icon name="palette" [size]="24" color="#2563EB" />
      <h2>Apariencia</h2>
    </div>
    <mat-slide-toggle [checked]="true">Modo oscuro</mat-slide-toggle>
    <div class="settings-section__footer">
      <button mat-flat-button class="btn-primary"><app-lucide-icon name="save" [size]="18" /> Guardar Preferencias</button>
    </div>
  </mat-card>
</div>

// _legacy-react/src/app/pages/Settings.tsx
import { useState } from 'react';
import { Box, Container, Paper, Typography, TextField, Button, Grid, Switch, FormControlLabel, Divider, Avatar } from '@mui/material';
import { Save, Bell, Lock, User, Building, Palette } from 'lucide-react';
import Sidebar from '../components/Sidebar';
import Topbar from '../components/Topbar';

export default function Settings() {
  const [notifications, setNotifications] = useState({
    email: true,
    sms: false,
    emergencias: true,
    citas: true,
    reportes: false,
  });

  return (
    <Box sx={{ display: 'flex', bgcolor: '#F8FAFC', minHeight: '100vh' }}>
      <Sidebar isAdmin={true} />

      <Box sx={{ flexGrow: 1, ml: '260px' }}>
        <Topbar userName="Dr. Juan Pérez" userRole="Veterinario Principal" />

        <Container maxWidth="lg" sx={{ mt: 10, py: 4 }}>
          <Typography variant="h4" sx={{ fontWeight: 700, color: '#1E293B', mb: 4 }}>
            Configuración
          </Typography>

          <Grid container spacing={3}>
            {/* Profile Settings */}
            <Grid item xs={12}>
              <Paper sx={{ p: 4, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
                  <User size={24} color="#2563EB" />
                  <Typography variant="h6" sx={{ ml: 2, fontWeight: 600 }}>
                    Perfil Personal
                  </Typography>
                </Box>

                <Grid container spacing={3}>
                  <Grid item xs={12} md={3}>
                    <Box sx={{ textAlign: 'center' }}>
                      <Avatar
                        sx={{
                          width: 120,
                          height: 120,
                          bgcolor: '#2563EB',
                          fontSize: '2.5rem',
                          mx: 'auto',
                          mb: 2,
                        }}
                      >
                        JP
                      </Avatar>
                      <Button variant="outlined" size="small">
                        Cambiar Foto
                      </Button>
                    </Box>
                  </Grid>

                  <Grid item xs={12} md={9}>
                    <Grid container spacing={2}>
                      <Grid item xs={12} sm={6}>
                        <TextField fullWidth label="Nombre" defaultValue="Dr. Juan Pérez" />
                      </Grid>
                      <Grid item xs={12} sm={6}>
                        <TextField fullWidth label="Correo Electrónico" defaultValue="juan.perez@petalert.com" />
                      </Grid>
                      <Grid item xs={12} sm={6}>
                        <TextField fullWidth label="Teléfono" defaultValue="+1 234-567-8901" />
                      </Grid>
                      <Grid item xs={12} sm={6}>
                        <TextField fullWidth label="Especialidad" defaultValue="Cirugía General" />
                      </Grid>
                      <Grid item xs={12}>
                        <TextField
                          fullWidth
                          label="Biografía"
                          multiline
                          rows={3}
                          defaultValue="Veterinario con 10 años de experiencia en cirugía general y emergencias."
                        />
                      </Grid>
                    </Grid>
                  </Grid>
                </Grid>

                <Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 3 }}>
                  <Button
                    variant="contained"
                    startIcon={<Save size={18} />}
                    sx={{
                      bgcolor: '#2563EB',
                      '&:hover': { bgcolor: '#1E40AF' },
                      px: 3,
                      fontWeight: 600,
                    }}
                  >
                    Guardar Cambios
                  </Button>
                </Box>
              </Paper>
            </Grid>

            {/* Clinic Settings */}
            <Grid item xs={12}>
              <Paper sx={{ p: 4, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
                  <Building size={24} color="#2563EB" />
                  <Typography variant="h6" sx={{ ml: 2, fontWeight: 600 }}>
                    Información de la Clínica
                  </Typography>
                </Box>

                <Grid container spacing={2}>
                  <Grid item xs={12} sm={6}>
                    <TextField fullWidth label="Nombre de la Clínica" defaultValue="Clínica Veterinaria PetAlert" />
                  </Grid>
                  <Grid item xs={12} sm={6}>
                    <TextField fullWidth label="Teléfono Principal" defaultValue="+1 800-PET-ALERT" />
                  </Grid>
                  <Grid item xs={12}>
                    <TextField
                      fullWidth
                      label="Dirección"
                      defaultValue="123 Calle Principal, Ciudad, País"
                    />
                  </Grid>
                  <Grid item xs={12} sm={6}>
                    <TextField fullWidth label="Horario de Atención" defaultValue="Lun-Vie: 8AM - 8PM" />
                  </Grid>
                  <Grid item xs={12} sm={6}>
                    <TextField fullWidth label="Email de Contacto" defaultValue="info@petalert.com" />
                  </Grid>
                </Grid>

                <Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 3 }}>
                  <Button
                    variant="contained"
                    startIcon={<Save size={18} />}
                    sx={{
                      bgcolor: '#2563EB',
                      '&:hover': { bgcolor: '#1E40AF' },
                      px: 3,
                      fontWeight: 600,
                    }}
                  >
                    Guardar Cambios
                  </Button>
                </Box>
              </Paper>
            </Grid>

            {/* Notifications */}
            <Grid item xs={12}>
              <Paper sx={{ p: 4, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
                  <Bell size={24} color="#2563EB" />
                  <Typography variant="h6" sx={{ ml: 2, fontWeight: 600 }}>
                    Notificaciones
                  </Typography>
                </Box>

                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                  <FormControlLabel
                    control={
                      <Switch
                        checked={notifications.email}
                        onChange={(e) =>
                          setNotifications({ ...notifications, email: e.target.checked })
                        }
                      />
                    }
                    label="Notificaciones por correo electrónico"
                  />
                  <FormControlLabel
                    control={
                      <Switch
                        checked={notifications.sms}
                        onChange={(e) =>
                          setNotifications({ ...notifications, sms: e.target.checked })
                        }
                      />
                    }
                    label="Notificaciones por SMS"
                  />

                  <Divider sx={{ my: 2 }} />

                  <Typography variant="body2" sx={{ fontWeight: 600, color: '#64748B' }}>
                    Tipos de Notificaciones
                  </Typography>

                  <FormControlLabel
                    control={
                      <Switch
                        checked={notifications.emergencias}
                        onChange={(e) =>
                          setNotifications({ ...notifications, emergencias: e.target.checked })
                        }
                      />
                    }
                    label="Alertas de emergencias"
                  />
                  <FormControlLabel
                    control={
                      <Switch
                        checked={notifications.citas}
                        onChange={(e) =>
                          setNotifications({ ...notifications, citas: e.target.checked })
                        }
                      />
                    }
                    label="Recordatorios de citas"
                  />
                  <FormControlLabel
                    control={
                      <Switch
                        checked={notifications.reportes}
                        onChange={(e) =>
                          setNotifications({ ...notifications, reportes: e.target.checked })
                        }
                      />
                    }
                    label="Reportes semanales"
                  />
                </Box>

                <Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 3 }}>
                  <Button
                    variant="contained"
                    startIcon={<Save size={18} />}
                    sx={{
                      bgcolor: '#2563EB',
                      '&:hover': { bgcolor: '#1E40AF' },
                      px: 3,
                      fontWeight: 600,
                    }}
                  >
                    Guardar Preferencias
                  </Button>
                </Box>
              </Paper>
            </Grid>

            {/* Security */}
            <Grid item xs={12}>
              <Paper sx={{ p: 4, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
                  <Lock size={24} color="#2563EB" />
                  <Typography variant="h6" sx={{ ml: 2, fontWeight: 600 }}>
                    Seguridad
                  </Typography>
                </Box>

                <Grid container spacing={2}>
                  <Grid item xs={12}>
                    <TextField
                      fullWidth
                      type="password"
                      label="Contraseña Actual"
                      placeholder="Ingresa tu contraseña actual"
                    />
                  </Grid>
                  <Grid item xs={12} sm={6}>
                    <TextField
                      fullWidth
                      type="password"
                      label="Nueva Contraseña"
                      placeholder="Ingresa nueva contraseña"
                    />
                  </Grid>
                  <Grid item xs={12} sm={6}>
                    <TextField
                      fullWidth
                      type="password"
                      label="Confirmar Contraseña"
                      placeholder="Confirma tu nueva contraseña"
                    />
                  </Grid>
                </Grid>

                <Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 3 }}>
                  <Button
                    variant="contained"
                    startIcon={<Lock size={18} />}
                    sx={{
                      bgcolor: '#2563EB',
                      '&:hover': { bgcolor: '#1E40AF' },
                      px: 3,
                      fontWeight: 600,
                    }}
                  >
                    Cambiar Contraseña
                  </Button>
                </Box>
              </Paper>
            </Grid>

            {/* Theme */}
            <Grid item xs={12}>
              <Paper sx={{ p: 4, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
                  <Palette size={24} color="#2563EB" />
                  <Typography variant="h6" sx={{ ml: 2, fontWeight: 600 }}>
                    Apariencia
                  </Typography>
                </Box>

                <FormControlLabel
                  control={<Switch defaultChecked />}
                  label="Modo oscuro"
                />

                <Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 3 }}>
                  <Button
                    variant="contained"
                    startIcon={<Save size={18} />}
                    sx={{
                      bgcolor: '#2563EB',
                      '&:hover': { bgcolor: '#1E40AF' },
                      px: 3,
                      fontWeight: 600,
                    }}
                  >
                    Guardar Preferencias
                  </Button>
                </Box>
              </Paper>
            </Grid>
          </Grid>
        </Container>
      </Box>
    </Box>
  );
}
