// src/app/pages/admin/users/users.component.ts
import { Component, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatChipsModule } from '@angular/material/chips';
import { MatTableModule } from '@angular/material/table';
import { LucideIconComponent } from '../../../shared/components/lucide-icon/lucide-icon.component';

const users = [
  { id: 1, name: 'Dr. Juan Pérez', email: 'juan.perez@petalert.com', phone: '+1 234-567-8901', role: 'Veterinario', specialty: 'Cirugía General', status: 'Activo', patients: 45 },
  { id: 2, name: 'Dra. María González', email: 'maria.gonzalez@petalert.com', phone: '+1 234-567-8902', role: 'Veterinario', specialty: 'Medicina Interna', status: 'Activo', patients: 38 },
  { id: 3, name: 'Dr. Luis Martínez', email: 'luis.martinez@petalert.com', phone: '+1 234-567-8903', role: 'Veterinario', specialty: 'Emergencias', status: 'Activo', patients: 52 },
  { id: 4, name: 'Dra. Ana García', email: 'ana.garcia@petalert.com', phone: '+1 234-567-8904', role: 'Veterinario', specialty: 'Dermatología', status: 'Activo', patients: 28 },
  { id: 5, name: 'María López', email: 'maria.lopez@email.com', phone: '+1 234-567-8905', role: 'Cliente', specialty: '-', status: 'Activo', patients: 2 },
  { id: 6, name: 'Carlos Ruiz', email: 'carlos.ruiz@email.com', phone: '+1 234-567-8906', role: 'Cliente', specialty: '-', status: 'Activo', patients: 1 },
  { id: 7, name: 'Ana Rodríguez', email: 'ana.rodriguez@email.com', phone: '+1 234-567-8907', role: 'Cliente', specialty: '-', status: 'Activo', patients: 3 },
  { id: 8, name: 'Pedro Sánchez', email: 'pedro.sanchez@email.com', phone: '+1 234-567-8908', role: 'Cliente', specialty: '-', status: 'Inactivo', patients: 1 },
];

type RoleFilter = 'all' | 'Veterinario' | 'Cliente';

@Component({
  selector: 'app-users',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatChipsModule,
    MatTableModule,
    LucideIconComponent,
  ],
  templateUrl: './users.component.html',
  styleUrl: './users.component.scss',
})
export class UsersComponent {
  readonly users = users;
  readonly displayedColumns = ['usuario', 'contacto', 'rol', 'especialidad', 'mascotas', 'estado', 'acciones'];

  searchTerm = signal('');
  filterRole = signal<RoleFilter>('all');

  veterinariosCount = users.filter((u) => u.role === 'Veterinario').length;
  clientesCount = users.filter((u) => u.role === 'Cliente').length;

  filteredUsers = computed(() => {
    const term = this.searchTerm().toLowerCase();
    const role = this.filterRole();
    return users.filter((user) => {
      const matchesSearch =
        user.name.toLowerCase().includes(term) || user.email.toLowerCase().includes(term);
      const matchesRole = role === 'all' || user.role === role;
      return matchesSearch && matchesRole;
    });
  });

  setFilterRole(role: RoleFilter): void {
    this.filterRole.set(role);
  }

  getRoleClass(role: string): string {
    return role === 'Veterinario' ? 'role--vet' : 'role--client';
  }

  getStatusClass(status: string): string {
    return status === 'Activo' ? 'status--active' : 'status--inactive';
  }
}

<div class="page-container">
  <div class="page-header">
    <div>
      <h1 class="page-title">Gestión de Usuarios</h1>
      <p class="page-subtitle">Administra veterinarios y clientes de la plataforma</p>
    </div>
    <button mat-flat-button class="btn-primary">
      <app-lucide-icon name="plus" [size]="20" />
      Nuevo Usuario
    </button>
  </div>

  <div class="filter-stats">
    <mat-card class="filter-stat" [class.filter-stat--active]="filterRole() === 'all'" (click)="setFilterRole('all')">
      <p class="filter-stat__value filter-stat__value--primary">{{ users.length }}</p>
      <p class="filter-stat__label">Total Usuarios</p>
    </mat-card>
    <mat-card class="filter-stat" [class.filter-stat--active]="filterRole() === 'Veterinario'" (click)="setFilterRole('Veterinario')">
      <p class="filter-stat__value filter-stat__value--primary">{{ veterinariosCount }}</p>
      <p class="filter-stat__label">Veterinarios</p>
    </mat-card>
    <mat-card class="filter-stat" [class.filter-stat--active]="filterRole() === 'Cliente'" (click)="setFilterRole('Cliente')">
      <p class="filter-stat__value filter-stat__value--secondary">{{ clientesCount }}</p>
      <p class="filter-stat__label">Clientes</p>
    </mat-card>
  </div>

  <mat-card class="search-card">
    <mat-form-field appearance="outline" class="search-field">
      <app-lucide-icon matPrefix name="search" [size]="20" color="#64748B" />
      <input matInput placeholder="Buscar por nombre o correo..." [ngModel]="searchTerm()" (ngModelChange)="searchTerm.set($event)" />
    </mat-form-field>
  </mat-card>

  <mat-card class="table-card">
    <table mat-table [dataSource]="filteredUsers()" class="users-table">
      <ng-container matColumnDef="usuario">
        <th mat-header-cell *matHeaderCellDef>Usuario</th>
        <td mat-cell *matCellDef="let user">
          <div class="user-cell">
            <div class="user-cell__avatar" [class.user-cell__avatar--vet]="user.role === 'Veterinario'">
              {{ user.name.charAt(0) }}
            </div>
            <div>
              <p class="user-cell__name">{{ user.name }}</p>
              <p class="user-cell__id">ID: {{ user.id }}</p>
            </div>
          </div>
        </td>
      </ng-container>
      <ng-container matColumnDef="contacto">
        <th mat-header-cell *matHeaderCellDef>Contacto</th>
        <td mat-cell *matCellDef="let user">
          <div class="contact-cell">
            <div><app-lucide-icon name="mail" [size]="14" color="#64748B" /> {{ user.email }}</div>
            <div><app-lucide-icon name="phone" [size]="14" color="#64748B" /> {{ user.phone }}</div>
          </div>
        </td>
      </ng-container>
      <ng-container matColumnDef="rol">
        <th mat-header-cell *matHeaderCellDef>Rol</th>
        <td mat-cell *matCellDef="let user">
          <mat-chip [ngClass]="getRoleClass(user.role)">
            <app-lucide-icon [name]="user.role === 'Veterinario' ? 'shield' : 'users'" [size]="14" />
            {{ user.role }}
          </mat-chip>
        </td>
      </ng-container>
      <ng-container matColumnDef="especialidad">
        <th mat-header-cell *matHeaderCellDef>Especialidad</th>
        <td mat-cell *matCellDef="let user">{{ user.specialty }}</td>
      </ng-container>
      <ng-container matColumnDef="mascotas">
        <th mat-header-cell *matHeaderCellDef>Mascotas</th>
        <td mat-cell *matCellDef="let user"><strong>{{ user.patients }}</strong></td>
      </ng-container>
      <ng-container matColumnDef="estado">
        <th mat-header-cell *matHeaderCellDef>Estado</th>
        <td mat-cell *matCellDef="let user">
          <mat-chip [ngClass]="getStatusClass(user.status)">{{ user.status }}</mat-chip>
        </td>
      </ng-container>
      <ng-container matColumnDef="acciones">
        <th mat-header-cell *matHeaderCellDef>Acciones</th>
        <td mat-cell *matCellDef="let user">
          <div class="actions-cell">
            <button mat-stroked-button>Ver</button>
            <button mat-stroked-button color="warn">Editar</button>
          </div>
        </td>
      </ng-container>
      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
    </table>
  </mat-card>
</div>

// _legacy-react/src/app/pages/Users.tsx
import { useState } from 'react';
import { Box, Container, Paper, Typography, Grid, Button, TextField, InputAdornment, Chip, Avatar, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from '@mui/material';
import { Search, Plus, Users as UsersIcon, Mail, Phone, Shield } from 'lucide-react';
import Sidebar from '../components/Sidebar';
import Topbar from '../components/Topbar';

const users = [
  {
    id: 1,
    name: 'Dr. Juan Pérez',
    email: 'juan.perez@petalert.com',
    phone: '+1 234-567-8901',
    role: 'Veterinario',
    specialty: 'Cirugía General',
    status: 'Activo',
    patients: 45,
  },
  {
    id: 2,
    name: 'Dra. María González',
    email: 'maria.gonzalez@petalert.com',
    phone: '+1 234-567-8902',
    role: 'Veterinario',
    specialty: 'Medicina Interna',
    status: 'Activo',
    patients: 38,
  },
  {
    id: 3,
    name: 'Dr. Luis Martínez',
    email: 'luis.martinez@petalert.com',
    phone: '+1 234-567-8903',
    role: 'Veterinario',
    specialty: 'Emergencias',
    status: 'Activo',
    patients: 52,
  },
  {
    id: 4,
    name: 'Dra. Ana García',
    email: 'ana.garcia@petalert.com',
    phone: '+1 234-567-8904',
    role: 'Veterinario',
    specialty: 'Dermatología',
    status: 'Activo',
    patients: 28,
  },
  {
    id: 5,
    name: 'María López',
    email: 'maria.lopez@email.com',
    phone: '+1 234-567-8905',
    role: 'Cliente',
    specialty: '-',
    status: 'Activo',
    patients: 2,
  },
  {
    id: 6,
    name: 'Carlos Ruiz',
    email: 'carlos.ruiz@email.com',
    phone: '+1 234-567-8906',
    role: 'Cliente',
    specialty: '-',
    status: 'Activo',
    patients: 1,
  },
  {
    id: 7,
    name: 'Ana Rodríguez',
    email: 'ana.rodriguez@email.com',
    phone: '+1 234-567-8907',
    role: 'Cliente',
    specialty: '-',
    status: 'Activo',
    patients: 3,
  },
  {
    id: 8,
    name: 'Pedro Sánchez',
    email: 'pedro.sanchez@email.com',
    phone: '+1 234-567-8908',
    role: 'Cliente',
    specialty: '-',
    status: 'Inactivo',
    patients: 1,
  },
];

export default function Users() {
  const [searchTerm, setSearchTerm] = useState('');
  const [filterRole, setFilterRole] = useState<'all' | 'Veterinario' | 'Cliente'>('all');

  const getRoleColor = (role: string) => {
    return role === 'Veterinario'
      ? { bg: '#DBEAFE', color: '#2563EB' }
      : { bg: '#D1FAE5', color: '#10B981' };
  };

  const getStatusColor = (status: string) => {
    return status === 'Activo'
      ? { bg: '#D1FAE5', color: '#10B981' }
      : { bg: '#FEE2E2', color: '#EF4444' };
  };

  const filteredUsers = users.filter((user) => {
    const matchesSearch =
      user.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      user.email.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesRole = filterRole === 'all' || user.role === filterRole;
    return matchesSearch && matchesRole;
  });

  const veterinarios = users.filter((u) => u.role === 'Veterinario').length;
  const clientes = users.filter((u) => u.role === 'Cliente').length;

  return (
    <Box sx={{ display: 'flex', bgcolor: '#F8FAFC', minHeight: '100vh' }}>
      <Sidebar isAdmin={true} />

      <Box sx={{ flexGrow: 1, ml: '260px' }}>
        <Topbar userName="Dr. Juan Pérez" userRole="Veterinario Principal" />

        <Container maxWidth="xl" sx={{ mt: 10, py: 4 }}>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 4 }}>
            <Box>
              <Typography variant="h4" sx={{ fontWeight: 700, color: '#1E293B' }}>
                Gestión de Usuarios
              </Typography>
              <Typography variant="body2" sx={{ color: '#64748B', mt: 1 }}>
                Administra veterinarios y clientes de la plataforma
              </Typography>
            </Box>
            <Button
              variant="contained"
              startIcon={<Plus size={20} />}
              sx={{
                bgcolor: '#2563EB',
                '&:hover': { bgcolor: '#1E40AF' },
                px: 3,
                py: 1.5,
                fontWeight: 600,
              }}
            >
              Nuevo Usuario
            </Button>
          </Box>

          {/* Stats */}
          <Grid container spacing={3} sx={{ mb: 4 }}>
            <Grid item xs={12} sm={4}>
              <Paper
                sx={{
                  p: 3,
                  borderRadius: 3,
                  border: '1px solid #E2E8F0',
                  textAlign: 'center',
                  cursor: 'pointer',
                  bgcolor: filterRole === 'all' ? '#EFF6FF' : 'white',
                  transition: 'all 0.2s',
                  '&:hover': { bgcolor: '#F8FAFC' },
                }}
                onClick={() => setFilterRole('all')}
              >
                <Typography variant="h3" sx={{ fontWeight: 700, color: '#2563EB', mb: 1 }}>
                  {users.length}
                </Typography>
                <Typography variant="body2" sx={{ color: '#64748B' }}>
                  Total Usuarios
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={12} sm={4}>
              <Paper
                sx={{
                  p: 3,
                  borderRadius: 3,
                  border: '1px solid #E2E8F0',
                  textAlign: 'center',
                  cursor: 'pointer',
                  bgcolor: filterRole === 'Veterinario' ? '#EFF6FF' : 'white',
                  transition: 'all 0.2s',
                  '&:hover': { bgcolor: '#F8FAFC' },
                }}
                onClick={() => setFilterRole('Veterinario')}
              >
                <Typography variant="h3" sx={{ fontWeight: 700, color: '#2563EB', mb: 1 }}>
                  {veterinarios}
                </Typography>
                <Typography variant="body2" sx={{ color: '#64748B' }}>
                  Veterinarios
                </Typography>
              </Paper>
            </Grid>
            <Grid item xs={12} sm={4}>
              <Paper
                sx={{
                  p: 3,
                  borderRadius: 3,
                  border: '1px solid #E2E8F0',
                  textAlign: 'center',
                  cursor: 'pointer',
                  bgcolor: filterRole === 'Cliente' ? '#EFF6FF' : 'white',
                  transition: 'all 0.2s',
                  '&:hover': { bgcolor: '#F8FAFC' },
                }}
                onClick={() => setFilterRole('Cliente')}
              >
                <Typography variant="h3" sx={{ fontWeight: 700, color: '#10B981', mb: 1 }}>
                  {clientes}
                </Typography>
                <Typography variant="body2" sx={{ color: '#64748B' }}>
                  Clientes
                </Typography>
              </Paper>
            </Grid>
          </Grid>

          {/* Search */}
          <Paper sx={{ p: 2, mb: 4, borderRadius: 3, border: '1px solid #E2E8F0' }}>
            <TextField
              fullWidth
              placeholder="Buscar por nombre o correo..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <Search size={20} color="#64748B" />
                  </InputAdornment>
                ),
              }}
              sx={{ '& .MuiOutlinedInput-root': { border: 'none' } }}
            />
          </Paper>

          {/* Users Table */}
          <TableContainer component={Paper} sx={{ borderRadius: 3, border: '1px solid #E2E8F0' }}>
            <Table>
              <TableHead>
                <TableRow sx={{ bgcolor: '#F8FAFC' }}>
                  <TableCell sx={{ fontWeight: 600 }}>Usuario</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Contacto</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Rol</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Especialidad</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Mascotas</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Estado</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Acciones</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {filteredUsers.map((user) => {
                  const roleColor = getRoleColor(user.role);
                  const statusColor = getStatusColor(user.status);
                  return (
                    <TableRow key={user.id} sx={{ '&:hover': { bgcolor: '#F8FAFC' } }}>
                      <TableCell>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                          <Avatar sx={{ bgcolor: roleColor.color }}>
                            {user.name.charAt(0)}
                          </Avatar>
                          <Box>
                            <Typography variant="body2" sx={{ fontWeight: 600 }}>
                              {user.name}
                            </Typography>
                            <Typography variant="caption" sx={{ color: '#64748B' }}>
                              ID: {user.id}
                            </Typography>
                          </Box>
                        </Box>
                      </TableCell>
                      <TableCell>
                        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 0.5 }}>
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <Mail size={14} color="#64748B" />
                            <Typography variant="caption" sx={{ color: '#64748B' }}>
                              {user.email}
                            </Typography>
                          </Box>
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <Phone size={14} color="#64748B" />
                            <Typography variant="caption" sx={{ color: '#64748B' }}>
                              {user.phone}
                            </Typography>
                          </Box>
                        </Box>
                      </TableCell>
                      <TableCell>
                        <Chip
                          label={user.role}
                          size="small"
                          icon={user.role === 'Veterinario' ? <Shield size={14} /> : <UsersIcon size={14} />}
                          sx={{
                            bgcolor: roleColor.bg,
                            color: roleColor.color,
                            fontWeight: 600,
                          }}
                        />
                      </TableCell>
                      <TableCell>
                        <Typography variant="body2">
                          {user.specialty}
                        </Typography>
                      </TableCell>
                      <TableCell>
                        <Typography variant="body2" sx={{ fontWeight: 600 }}>
                          {user.patients}
                        </Typography>
                      </TableCell>
                      <TableCell>
                        <Chip
                          label={user.status}
                          size="small"
                          sx={{
                            bgcolor: statusColor.bg,
                            color: statusColor.color,
                            fontWeight: 600,
                          }}
                        />
                      </TableCell>
                      <TableCell>
                        <Box sx={{ display: 'flex', gap: 1 }}>
                          <Button size="small" variant="outlined">
                            Ver
                          </Button>
                          <Button size="small" variant="outlined" color="error">
                            Editar
                          </Button>
                        </Box>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </TableContainer>
        </Container>
      </Box>
    </Box>
  );
}
