// _legacy-react/src/app/pages/Reports.tsx
import { Box, Container, Paper, Typography, Grid, Button, Select, MenuItem, FormControl, InputLabel } from '@mui/material';
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { Download, FileText, TrendingUp, Calendar, DollarSign } from 'lucide-react';
import Sidebar from '../components/Sidebar';
import Topbar from '../components/Topbar';

const monthlyData = [
  { month: 'Ene', consultas: 120, emergencias: 25, vacunas: 45, cirugias: 8, ingresos: 15000 },
  { month: 'Feb', consultas: 135, emergencias: 30, vacunas: 52, cirugias: 12, ingresos: 18500 },
  { month: 'Mar', consultas: 145, emergencias: 28, vacunas: 48, cirugias: 10, ingresos: 17200 },
  { month: 'Abr', consultas: 160, emergencias: 35, vacunas: 60, cirugias: 15, ingresos: 21000 },
  { month: 'May', consultas: 155, emergencias: 32, vacunas: 55, cirugias: 13, ingresos: 19800 },
];

const speciesDistribution = [
  { name: 'Perros', value: 210, color: '#2563EB' },
  { name: 'Gatos', value: 145, color: '#10B981' },
  { name: 'Aves', value: 35, color: '#F59E0B' },
  { name: 'Conejos', value: 22, color: '#A855F7' },
  { name: 'Otros', value: 18, color: '#64748B' },
];

const topTreatments = [
  { name: 'Vacunación', count: 260, percentage: 35 },
  { name: 'Consulta General', count: 195, percentage: 26 },
  { name: 'Emergencias', count: 150, percentage: 20 },
  { name: 'Cirugías', count: 58, percentage: 8 },
  { name: 'Tratamientos', count: 82, percentage: 11 },
];

export default function Reports() {
  return (
    <Box sx={{ display: 'flex', bgcolor: '#F8FAFC', minHeight: '100vh' }}>
      <Sidebar isAdmin={true} />

      <Box sx={{ flexGrow: 1, ml: '260px' }}>
        <Topbar userName="Dr. Juan Pérez" userRole="Veterinario Principal" />

        <Container maxWidth="xl" sx={{ mt: 10, py: 4 }}>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 4 }}>
            <Box>
              <Typography variant="h4" sx={{ fontWeight: 700, color: '#1E293B' }}>
                Reportes y Estadísticas
              </Typography>
              <Typography variant="body2" sx={{ color: '#64748B', mt: 1 }}>
                Análisis detallado del rendimiento de la clínica
              </Typography>
            </Box>
            <Box sx={{ display: 'flex', gap: 2 }}>
              <FormControl size="small" sx={{ minWidth: 150 }}>
                <InputLabel>Período</InputLabel>
                <Select defaultValue="mes" label="Período">
                  <MenuItem value="semana">Esta Semana</MenuItem>
                  <MenuItem value="mes">Este Mes</MenuItem>
                  <MenuItem value="trimestre">Trimestre</MenuItem>
                  <MenuItem value="año">Año</MenuItem>
                </Select>
              </FormControl>
              <Button
                variant="contained"
                startIcon={<Download size={20} />}
                sx={{
                  bgcolor: '#2563EB',
                  '&:hover': { bgcolor: '#1E40AF' },
                  px: 3,
                  fontWeight: 600,
                }}
              >
                Exportar PDF
              </Button>
            </Box>
          </Box>

          {/* Summary Cards */}
          <Grid container spacing={3} sx={{ mb: 4 }}>
            <Grid item xs={12} sm={6} md={3}>
              <Paper sx={{ p: 3, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <Box>
                    <Typography variant="body2" sx={{ color: '#64748B', mb: 1 }}>
                      Total Consultas
                    </Typography>
                    <Typography variant="h4" sx={{ fontWeight: 700, color: '#2563EB' }}>
                      715
                    </Typography>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 1 }}>
                      <TrendingUp size={16} color="#10B981" />
                      <Typography variant="caption" sx={{ color: '#10B981' }}>
                        +12% vs mes anterior
                      </Typography>
                    </Box>
                  </Box>
                  <Box sx={{ bgcolor: '#DBEAFE', p: 1.5, borderRadius: 2 }}>
                    <FileText size={24} color="#2563EB" />
                  </Box>
                </Box>
              </Paper>
            </Grid>

            <Grid item xs={12} sm={6} md={3}>
              <Paper sx={{ p: 3, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <Box>
                    <Typography variant="body2" sx={{ color: '#64748B', mb: 1 }}>
                      Ingresos Totales
                    </Typography>
                    <Typography variant="h4" sx={{ fontWeight: 700, color: '#10B981' }}>
                      $91.5K
                    </Typography>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 1 }}>
                      <TrendingUp size={16} color="#10B981" />
                      <Typography variant="caption" sx={{ color: '#10B981' }}>
                        +18% vs mes anterior
                      </Typography>
                    </Box>
                  </Box>
                  <Box sx={{ bgcolor: '#D1FAE5', p: 1.5, borderRadius: 2 }}>
                    <DollarSign size={24} color="#10B981" />
                  </Box>
                </Box>
              </Paper>
            </Grid>

            <Grid item xs={12} sm={6} md={3}>
              <Paper sx={{ p: 3, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <Box>
                    <Typography variant="body2" sx={{ color: '#64748B', mb: 1 }}>
                      Pacientes Activos
                    </Typography>
                    <Typography variant="h4" sx={{ fontWeight: 700, color: '#F59E0B' }}>
                      430
                    </Typography>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 1 }}>
                      <TrendingUp size={16} color="#10B981" />
                      <Typography variant="caption" sx={{ color: '#10B981' }}>
                        +8% vs mes anterior
                      </Typography>
                    </Box>
                  </Box>
                  <Box sx={{ bgcolor: '#FEF3C7', p: 1.5, borderRadius: 2 }}>
                    <Calendar size={24} color="#F59E0B" />
                  </Box>
                </Box>
              </Paper>
            </Grid>

            <Grid item xs={12} sm={6} md={3}>
              <Paper sx={{ p: 3, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <Box>
                    <Typography variant="body2" sx={{ color: '#64748B', mb: 1 }}>
                      Tasa Satisfacción
                    </Typography>
                    <Typography variant="h4" sx={{ fontWeight: 700, color: '#A855F7' }}>
                      98%
                    </Typography>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 1 }}>
                      <TrendingUp size={16} color="#10B981" />
                      <Typography variant="caption" sx={{ color: '#10B981' }}>
                        +2% vs mes anterior
                      </Typography>
                    </Box>
                  </Box>
                  <Box sx={{ bgcolor: '#F3E8FF', p: 1.5, borderRadius: 2 }}>
                    <TrendingUp size={24} color="#A855F7" />
                  </Box>
                </Box>
              </Paper>
            </Grid>
          </Grid>

          {/* Charts */}
          <Grid container spacing={3} sx={{ mb: 4 }}>
            <Grid item xs={12} lg={8}>
              <Paper sx={{ p: 3, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Typography variant="h6" sx={{ mb: 3, fontWeight: 600 }}>
                  Actividad Mensual
                </Typography>
                <ResponsiveContainer width="100%" height={350}>
                  <BarChart data={monthlyData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" />
                    <XAxis dataKey="month" stroke="#64748B" />
                    <YAxis stroke="#64748B" />
                    <Tooltip />
                    <Legend />
                    <Bar dataKey="consultas" fill="#2563EB" name="Consultas" />
                    <Bar dataKey="emergencias" fill="#EF4444" name="Emergencias" />
                    <Bar dataKey="vacunas" fill="#10B981" name="Vacunas" />
                    <Bar dataKey="cirugias" fill="#F59E0B" name="Cirugías" />
                  </BarChart>
                </ResponsiveContainer>
              </Paper>
            </Grid>

            <Grid item xs={12} lg={4}>
              <Paper sx={{ p: 3, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Typography variant="h6" sx={{ mb: 3, fontWeight: 600 }}>
                  Distribución por Especie
                </Typography>
                <ResponsiveContainer width="100%" height={350}>
                  <PieChart>
                    <Pie
                      data={speciesDistribution}
                      cx="50%"
                      cy="50%"
                      labelLine={false}
                      label={({ name, value }) => `${name}: ${value}`}
                      outerRadius={100}
                      fill="#8884d8"
                      dataKey="value"
                    >
                      {speciesDistribution.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </Paper>
            </Grid>
          </Grid>

          {/* Income Chart */}
          <Grid container spacing={3} sx={{ mb: 4 }}>
            <Grid item xs={12}>
              <Paper sx={{ p: 3, borderRadius: 3, border: '1px solid #E2E8F0' }}>
                <Typography variant="h6" sx={{ mb: 3, fontWeight: 600 }}>
                  Ingresos Mensuales
                </Typography>
                <ResponsiveContainer width="100%" height={300}>
                  <LineChart data={monthlyData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" />
                    <XAxis dataKey="month" stroke="#64748B" />
                    <YAxis stroke="#64748B" />
                    <Tooltip />
                    <Legend />
                    <Line
                      type="monotone"
                      dataKey="ingresos"
                      stroke="#10B981"
                      strokeWidth={3}
                      name="Ingresos ($)"
                      dot={{ r: 6 }}
                    />
                  </LineChart>
                </ResponsiveContainer>
              </Paper>
            </Grid>
          </Grid>

          {/* Top Treatments */}
          <Paper sx={{ p: 3, borderRadius: 3, border: '1px solid #E2E8F0' }}>
            <Typography variant="h6" sx={{ mb: 3, fontWeight: 600 }}>
              Servicios Más Solicitados
            </Typography>
            <Box>
              {topTreatments.map((treatment, index) => (
                <Box key={index} sx={{ mb: 3 }}>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                    <Typography variant="body2" sx={{ fontWeight: 600 }}>
                      {treatment.name}
                    </Typography>
                    <Typography variant="body2" sx={{ color: '#64748B' }}>
                      {treatment.count} servicios ({treatment.percentage}%)
                    </Typography>
                  </Box>
                  <Box sx={{ width: '100%', bgcolor: '#E2E8F0', borderRadius: 1, height: 8 }}>
                    <Box
                      sx={{
                        width: `${treatment.percentage}%`,
                        bgcolor: '#2563EB',
                        borderRadius: 1,
                        height: '100%',
                        transition: 'width 0.5s ease',
                      }}
                    />
                  </Box>
                </Box>
              ))}
            </Box>
          </Paper>
        </Container>
      </Box>
    </Box>
  );
}

// src/app/pages/admin/reports/reports.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  OnDestroy,
  ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { Chart, ChartConfiguration } from 'chart.js/auto';
import { LucideIconComponent } from '../../../shared/components/lucide-icon/lucide-icon.component';

const monthlyData = [
  { month: 'Ene', consultas: 120, emergencias: 25, vacunas: 45, cirugias: 8, ingresos: 15000 },
  { month: 'Feb', consultas: 135, emergencias: 30, vacunas: 52, cirugias: 12, ingresos: 18500 },
  { month: 'Mar', consultas: 145, emergencias: 28, vacunas: 48, cirugias: 10, ingresos: 17200 },
  { month: 'Abr', consultas: 160, emergencias: 35, vacunas: 60, cirugias: 15, ingresos: 21000 },
  { month: 'May', consultas: 155, emergencias: 32, vacunas: 55, cirugias: 13, ingresos: 19800 },
];

const speciesDistribution = [
  { name: 'Perros', value: 210, color: '#2563EB' },
  { name: 'Gatos', value: 145, color: '#10B981' },
  { name: 'Aves', value: 35, color: '#F59E0B' },
  { name: 'Conejos', value: 22, color: '#A855F7' },
  { name: 'Otros', value: 18, color: '#64748B' },
];

const topTreatments = [
  { name: 'Vacunación', count: 260, percentage: 35 },
  { name: 'Consulta General', count: 195, percentage: 26 },
  { name: 'Emergencias', count: 150, percentage: 20 },
  { name: 'Cirugías', count: 58, percentage: 8 },
  { name: 'Tratamientos', count: 82, percentage: 11 },
];

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule,
    MatFormFieldModule,
    MatSelectModule,
    LucideIconComponent,
  ],
  templateUrl: './reports.component.html',
  styleUrl: './reports.component.scss',
})
export class ReportsComponent implements AfterViewInit, OnDestroy {
  @ViewChild('barChartCanvas') barChartCanvas!: ElementRef<HTMLCanvasElement>;
  @ViewChild('pieChartCanvas') pieChartCanvas!: ElementRef<HTMLCanvasElement>;
  @ViewChild('lineChartCanvas') lineChartCanvas!: ElementRef<HTMLCanvasElement>;

  readonly monthlyData = monthlyData;
  readonly speciesDistribution = speciesDistribution;
  readonly topTreatments = topTreatments;
  period = 'mes';

  private barChart?: Chart;
  private pieChart?: Chart;
  private lineChart?: Chart;

  ngAfterViewInit(): void {
    this.initBarChart();
    this.initPieChart();
    this.initLineChart();
  }

  ngOnDestroy(): void {
    this.barChart?.destroy();
    this.pieChart?.destroy();
    this.lineChart?.destroy();
  }

  private initBarChart(): void {
    const ctx = this.barChartCanvas.nativeElement.getContext('2d');
    if (!ctx) return;
    const config: ChartConfiguration<'bar'> = {
      type: 'bar',
      data: {
        labels: monthlyData.map((d) => d.month),
        datasets: [
          { label: 'Consultas', data: monthlyData.map((d) => d.consultas), backgroundColor: '#2563EB' },
          { label: 'Emergencias', data: monthlyData.map((d) => d.emergencias), backgroundColor: '#EF4444' },
          { label: 'Vacunas', data: monthlyData.map((d) => d.vacunas), backgroundColor: '#10B981' },
          { label: 'Cirugías', data: monthlyData.map((d) => d.cirugias), backgroundColor: '#F59E0B' },
        ],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { position: 'bottom' } },
        scales: {
          x: { grid: { color: '#E2E8F0' }, ticks: { color: '#64748B' } },
          y: { grid: { color: '#E2E8F0' }, ticks: { color: '#64748B' } },
        },
      },
    };
    this.barChart = new Chart(ctx, config);
  }

  private initPieChart(): void {
    const ctx = this.pieChartCanvas.nativeElement.getContext('2d');
    if (!ctx) return;
    const config: ChartConfiguration<'pie'> = {
      type: 'pie',
      data: {
        labels: speciesDistribution.map((d) => d.name),
        datasets: [{ data: speciesDistribution.map((d) => d.value), backgroundColor: speciesDistribution.map((d) => d.color) }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { position: 'bottom' } },
      },
    };
    this.pieChart = new Chart(ctx, config);
  }

  private initLineChart(): void {
    const ctx = this.lineChartCanvas.nativeElement.getContext('2d');
    if (!ctx) return;
    const config: ChartConfiguration<'line'> = {
      type: 'line',
      data: {
        labels: monthlyData.map((d) => d.month),
        datasets: [{
          label: 'Ingresos ($)',
          data: monthlyData.map((d) => d.ingresos),
          borderColor: '#10B981',
          backgroundColor: 'rgba(16, 185, 129, 0.1)',
          borderWidth: 3,
          tension: 0.4,
          pointRadius: 6,
        }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { position: 'bottom' } },
        scales: {
          x: { grid: { color: '#E2E8F0' }, ticks: { color: '#64748B' } },
          y: { grid: { color: '#E2E8F0' }, ticks: { color: '#64748B' } },
        },
      },
    };
    this.lineChart = new Chart(ctx, config);
  }
}

<div class="page-container">
  <div class="page-header">
    <div>
      <h1 class="page-title">Reportes y Estadísticas</h1>
      <p class="page-subtitle">Análisis detallado del rendimiento de la clínica</p>
    </div>
    <div class="page-header__actions">
      <mat-form-field appearance="outline" class="period-select">
        <mat-label>Período</mat-label>
        <mat-select [(value)]="period">
          <mat-option value="semana">Esta Semana</mat-option>
          <mat-option value="mes">Este Mes</mat-option>
          <mat-option value="trimestre">Trimestre</mat-option>
          <mat-option value="año">Año</mat-option>
        </mat-select>
      </mat-form-field>
      <button mat-flat-button class="btn-primary">
        <app-lucide-icon name="download" [size]="20" />
        Exportar PDF
      </button>
    </div>
  </div>

  <div class="stats-grid">
    <mat-card class="summary-card">
      <div class="summary-card__row">
        <div>
          <p class="summary-card__label">Total Consultas</p>
          <p class="summary-card__value summary-card__value--primary">715</p>
          <div class="summary-card__trend">
            <app-lucide-icon name="trending-up" [size]="16" color="#10B981" />
            <span class="trend--up">+12% vs mes anterior</span>
          </div>
        </div>
        <div class="summary-card__icon summary-card__icon--primary">
          <app-lucide-icon name="file-text" [size]="24" color="#2563EB" />
        </div>
      </div>
    </mat-card>
    <mat-card class="summary-card">
      <div class="summary-card__row">
        <div>
          <p class="summary-card__label">Ingresos Totales</p>
          <p class="summary-card__value summary-card__value--secondary">$91.5K</p>
          <div class="summary-card__trend">
            <app-lucide-icon name="trending-up" [size]="16" color="#10B981" />
            <span class="trend--up">+18% vs mes anterior</span>
          </div>
        </div>
        <div class="summary-card__icon summary-card__icon--secondary">
          <app-lucide-icon name="dollar-sign" [size]="24" color="#10B981" />
        </div>
      </div>
    </mat-card>
    <mat-card class="summary-card">
      <div class="summary-card__row">
        <div>
          <p class="summary-card__label">Pacientes Activos</p>
          <p class="summary-card__value summary-card__value--warning">430</p>
          <div class="summary-card__trend">
            <app-lucide-icon name="trending-up" [size]="16" color="#10B981" />
            <span class="trend--up">+8% vs mes anterior</span>
          </div>
        </div>
        <div class="summary-card__icon summary-card__icon--warning">
          <app-lucide-icon name="calendar" [size]="24" color="#F59E0B" />
        </div>
      </div>
    </mat-card>
    <mat-card class="summary-card">
      <div class="summary-card__row">
        <div>
          <p class="summary-card__label">Tasa Satisfacción</p>
          <p class="summary-card__value summary-card__value--purple">98%</p>
          <div class="summary-card__trend">
            <app-lucide-icon name="trending-up" [size]="16" color="#10B981" />
            <span class="trend--up">+2% vs mes anterior</span>
          </div>
        </div>
        <div class="summary-card__icon summary-card__icon--purple">
          <app-lucide-icon name="trending-up" [size]="24" color="#A855F7" />
        </div>
      </div>
    </mat-card>
  </div>

  <div class="charts-grid charts-grid--reports">
    <mat-card class="chart-card chart-card--wide">
      <h2 class="chart-card__title">Actividad Mensual</h2>
      <div class="chart-card__canvas-wrap chart-card__canvas-wrap--tall">
        <canvas #barChartCanvas></canvas>
      </div>
    </mat-card>
    <mat-card class="chart-card">
      <h2 class="chart-card__title">Distribución por Especie</h2>
      <div class="chart-card__canvas-wrap chart-card__canvas-wrap--tall">
        <canvas #pieChartCanvas></canvas>
      </div>
    </mat-card>
  </div>

  <mat-card class="chart-card chart-card--full">
    <h2 class="chart-card__title">Ingresos Mensuales</h2>
    <div class="chart-card__canvas-wrap">
      <canvas #lineChartCanvas></canvas>
    </div>
  </mat-card>

  <mat-card class="treatments-card">
    <h2 class="chart-card__title">Servicios Más Solicitados</h2>
    @for (treatment of topTreatments; track treatment.name) {
      <div class="treatment-row">
        <div class="treatment-row__header">
          <span class="treatment-row__name">{{ treatment.name }}</span>
          <span class="treatment-row__count">{{ treatment.count }} servicios ({{ treatment.percentage }}%)</span>
        </div>
        <div class="treatment-row__bar-bg">
          <div class="treatment-row__bar" [style.width.%]="treatment.percentage"></div>
        </div>
      </div>
    }
  </mat-card>
</div>
